// <auto-generated />
namespace SentimentAnalysisApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FieldAddedMinedTextTwitterID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FieldAddedMinedTextTwitterID));
        
        string IMigrationMetadata.Id
        {
            get { return "201612061552422_FieldAdded-MinedText.TwitterID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
